# Generated by Django 3.0.6 on 2020-06-09 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_classcontaspagar_formapagamentorecebimento_situacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContasReceber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('data_expectativa', models.DateField(null=True)),
                ('data_recebimento', models.DateField(null=True)),
                ('valor', models.IntegerField(default=0)),
                ('classificacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.ClassContasReceber')),
                ('forma_recebimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.FormaPagamentoRecebimento')),
                ('situacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.Situacao')),
            ],
        ),
        migrations.CreateModel(
            name='ContasPagar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('data_vencimento', models.DateField(null=True)),
                ('data_pagamento', models.DateField(null=True)),
                ('valor', models.IntegerField(default=0)),
                ('classificacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.ClassContasPagar')),
                ('forma_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.FormaPagamentoRecebimento')),
                ('situacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.Situacao')),
            ],
        ),
    ]
